# Extreme Heat Events Exploration

**Objective:** Explore trends in extreme heat events in Canada using a direct CSV file and beginner-friendly charts.

**Dataset description:** This file summarizes long-term Canadian extreme heat trends (1948 to 2023). Each row represents a trend category, with counts (`Number of Stations`) and percentages (`Percentage`) describing how many monitoring stations fit that trend.

**Data source(s):**
- Dataset page: https://open.canada.ca/data/en/dataset/2cc1ad59-97cf-4652-839a-7cfaa943ebcf
- English CSV: https://www.canada.ca/content/dam/eccc/documents/csv/cesindicators/extreme-heat-events/2025/cumulative-days-summary.csv
- French CSV: https://www.canada.ca/content/dam/eccc/documents/csv/cesindicators/extreme-heat-events/2025/cumulatif-jours-sommaire.csv

**Date/author:** 2026-03-11, Peter

## Step 1: Import our libraries

In Python, `import` loads tools from libraries so we can use them in our notebook.

- `pandas` (as `pd`) helps us load and work with table data.
- `plotly.express` (as `px`) helps us create charts quickly.

We run this setup cell once near the top of the notebook.

In [26]:
import pandas as pd
import plotly.express as px

## Step 2: Load the CSV and preview the table

This cell does three things in order:
1. Stores the dataset URL in a variable.
2. Uses `pd.read_csv(...)` to load the file into a DataFrame called `df`.
3. Shows the first five rows with `df.head()` so we can verify the data loaded correctly.

**Quick vocabulary:**
- A **DataFrame** is pandas' table object (rows and columns, like a spreadsheet).
- We name it `df` as a short common name for "data frame."
- In `df.head()` or `df.dropna()`, the part after the dot is usually a **method** (an action).
- In `df.columns`, the part after the dot is a **property/attribute** (stored information about the table).

In [27]:
data_url = "https://www.canada.ca/content/dam/eccc/documents/csv/cesindicators/extreme-heat-events/2025/cumulative-days-summary.csv"
df = pd.read_csv(data_url)
df.head()

,"Trends in the cumulative number of days under extreme heat conditions, Canada, 1948 to 2023",Unnamed: 1,Unnamed: 2
0,NaN,NaN,NaN
1,Trends,Number of stations,Percentage
2,Increase (Statistically significant),128,19%
3,Increase (Not statistically significant),283,42%
4,Increase (Total),411,60%

## Step 3: Display the column names

Before graphing, we first list the column names so we know what fields are available in the dataset.

In [28]:
display(df.columns)

Index(['Trends in the cumulative number of days under extreme heat conditions, Canada, 1948 to 2023',
       'Unnamed: 1', 'Unnamed: 2'],
      dtype='str')

## Step 4: Rename key columns

Some current column names are not suitable for analysis.
One is very long, and others are generic placeholders like `Unnamed: 1` and `Unnamed: 2`.
So we will rename them to short, clear names we can use easily in charts and code.

For this specific table, we can set all column names at once because it has exactly three columns.
In more complex datasets (extra columns or changing column order), use targeted renaming so you only change the columns you intend.

In [29]:
df.columns = ["Trend", "Number of Stations", "Percentage"]
display(df.columns)

Index(['Trend', 'Number of Stations', 'Percentage'], dtype='str')

## Step 5: View the full table

Display the entire DataFrame so students can see exactly what needs to be fixed.

In [30]:
display(df)

,Trend,Number of Stations,Percentage
0,NaN,NaN,NaN
1,Trends,Number of stations,Percentage
2,Increase (Statistically significant),128,19%
3,Increase (Not statistically significant),283,42%
4,Increase (Total),411,60%
5,Decrease (Statistically significant),3,<1%
6,Decrease (Not statistically significant),124,18%
7,Decrease (Total),127,19%
8,Insufficient events,143,21%
9,NaN,NaN,NaN
10,Note: Percentages may not add up to 100 due to...,NaN,NaN
11,Source: Environment and Climate Change Canada ...,NaN,NaN
12,Available on the Environmental indicators webs...,NaN,NaN

A good first cleanup step is to remove rows that contain `NaN` values.

`NaN` means "Not a Number." In pandas, it marks missing or invalid data.
If a row has missing values, it can cause problems in calculations and charts.

## Step 6: Delete rows with NaN values

`df.dropna()` creates a version of the table with any row containing `NaN` removed.
`copy()` then makes that result an independent DataFrame, which is safer for later edits.
Finally, we assign it back to `df` so the cleaned table replaces the original one.

In [31]:
df = df.dropna().copy()
display(df)

                                      Trend  Number of Stations  Percentage
1                                    Trends  Number of stations  Percentage
2      Increase (Statistically significant)                 128         19%
3  Increase (Not statistically significant)                 283         42%
4                          Increase (Total)                 411         60%
5      Decrease (Statistically significant)                   3         <1%
6  Decrease (Not statistically significant)                 124         18%
7                          Decrease (Total)                 127         19%
8                       Insufficient events                 143         21%

We still need to remove line number 1 from the table.
That row is not part of the cleaned data we want to analyze.

How this line works:
- `df.drop(...)` means "return a new DataFrame with some rows/columns removed."
- `index=1` means remove the row whose index label is `1`.
- `errors="ignore"` means: if index `1` is not present, do not crash; just continue.
- `.copy()` makes a separate DataFrame object, which helps avoid later warning/side-effect issues.
- `df = ...` assigns the result back to `df` so the change is kept.

In [32]:
df = df.drop(index=1, errors="ignore").copy()
display(df)

                                      Trend Number of Stations Percentage
2      Increase (Statistically significant)                128        19%
3  Increase (Not statistically significant)                283        42%
4                          Increase (Total)                411        60%
5      Decrease (Statistically significant)                  3        <1%
6  Decrease (Not statistically significant)                124        18%
7                          Decrease (Total)                127        19%
8                       Insufficient events                143        21%

## Step 7: Convert Number of Stations to numeric

Convert `Number of Stations` from text values to numeric values.

In [33]:
df["Number of Stations"] = pd.to_numeric(df["Number of Stations"], errors="coerce")

## Step 8: Build a bar chart

Create a bar chart using `Trend` versus `Number of Stations`.

In [34]:
fig = px.bar(
    df,
    x="Trend",
    y="Number of Stations",
    title="Number of Stations by Trend"
)
fig.show()

---
### Open In Colab
[Open this notebook in Google Colab](https://colab.research.google.com/github/Peter/ICD2O-OSC-2026-Project-Plan-Team-2/blob/main/notebooks/csv/extreme-heat-events-exploration.ipynb)